FROM amd64/alpine:3.13@sha256:4661fb57f7890b9145907a1fe2555091d333ff3d28db86c3bb906f6a2be93c87

LABEL maintainer="gclm <gclmit@163.com>" \
  org.label-schema.name="Drone GitHub Release" \
  org.label-schema.vendor="Gclmit" \
  org.label-schema.schema-version="1.0"
LABEL org.opencontainers.image.authors="gclmit@163.com"
LABEL org.opencontainers.image.title="drone-github-release"
LABEL org.opencontainers.image.url="https://github.com/gclm/drone-github-release"
LABEL org.opencontainers.image.source="https://github.com/gclm/drone-github-release"
LABEL org.opencontainers.image.documentation="https://github.com/gclm/drone-github-release"


ADD release/linux/amd64/drone-github-release /bin/
ENTRYPOINT [ "/bin/drone-github-release" ]
